Update Build_Lenovo_sm8750.yml

diff --git a/.github/workflows/Build_Lenovo_sm8750.yml b/.github/workflows/Build_Lenovo_sm8750.yml
--- a/.github/workflows/Build_Lenovo_sm8750.yml
+++ b/.github/workflows/Build_Lenovo_sm8750.yml
@@ -195,19 +195,33 @@ jobs:
       - name: ⚙️ Set SuKiSU Ultra (设置SuKiSU Ultra)
         id: ksu_version
         run: |
-            cd kernel_workspace
-            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/setup.sh" | bash -s susfs-main
-            cd KernelSU
-            KSU_VERSION=$(expr "$(git rev-list --count main)" + 37185 2>/dev/null || echo 114514)
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-             cp "${GITHUB_WORKSPACE}/.github/workflows/tools/setup.bin" ./
-            chmod +x setup.bin
-            if [ ! -f "kernel/Makefile" ]; then
-              echo "::error ::kernel/Makefile"
-              ls -la
-              exit 1
-            fi
-            ./setup.bin
+          cd kernel_workspace
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/setup.sh" | bash -s susfs-main
+          cd KernelSU
+    
+          # 创建自定义版本信息
+          cat > custom_version.txt << EOF
+      -- SukiSU-Ultra version (GitHub): 40168
+      -- SukiSU-Ultra version (Github): v4.0.0-ad902675-@yu
+      -- Supported Unofficial Manager: 5ec1cff (GKI) rsuntk (Non-GKI) ShirkNeko udochina (GKI and non-GKI and KPM)
+      -- SukiSU: SUSFS_INLINE_HOOK
+      -- KERNEL_VERSION: 6.6
+      -- KERNEL_TYPE: GKI 2.0
+      -- KPM is enabled
+      EOF
+    
+          KSU_VERSION=$(expr "$(git rev-list --count main)" + 37185 2>/dev/null || echo 114514)
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          cp "${GITHUB_WORKSPACE}/.github/workflows/tools/setup.bin" ./
+          chmod +x setup.bin
+          if [ ! -f "kernel/Makefile" ]; then
+            echo "::error ::kernel/Makefile"
+           ls -la
+            exit 1
+          fi
+        ./setup.bin
+        # 显示自定义版本信息
+          cat custom_version.txt
 
       - name: 🔧 Set up SUSFS (配置 SUSFS)
         env:
